ARG UBUNTU_RELEASE=26.04
ARG BASE_IMAGE=scratch-alias
ARG USERNAME
ARG USER_ID
ARG GROUP_ID

FROM ubuntu:$UBUNTU_RELEASE AS builder

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ca-certificates \
        build-essential pkgconf libssl-dev \
        rust-1.93-all cargo rustc \
        vim git \
        hyperfine ripgrep cargo-auditable \
        bash fish \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

COPY .env /tmp/.env
RUN . /tmp/.env && rm /tmp/.env && \
    sed -i 's/^UID_MAX.*/UID_MAX 9999999999/' /etc/login.defs && \
    groupadd --gid ${GROUP_ID} users_group_name && \
    useradd --uid ${USER_ID} --gid ${GROUP_ID} -s /usr/bin/fish -m --badname ${USERNAME} && \
    mkdir -p /etc/sudoers.d && \
    echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} && \
    chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}

USER root

FROM ${BASE_IMAGE}
COPY --from=builder / /

EXPOSE 8000 8080
